# Generated by Django 5.0.2 on 2024-03-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='url',
            field=models.TextField(default=None),
        ),
    ]
