# Generated by Django 5.0.2 on 2024-03-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_stream_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='url',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
